name: biblical_verse_segmentation
description: Segmentador especializado para extraer versos bíblicos con su estructura jerárquica completa (libro, capítulo, verso) manteniendo el orden secuencial y generando metadatos de navegación
segmenter: biblical_verse_segmentation
file_types:
  - txt
  - docx
  - pdf
  - rtf
  - html
thresholds:
  min_verse_length: 10
  max_verse_length: 2000
  min_chapter_verses: 1
  max_chapter_verses: 200
  book_title_confidence: 0.85
  verse_number_confidence: 0.90
  chapter_detection_confidence: 0.80
  text_continuity_threshold: 0.75
post_processor: biblical_structure_validator
metadata_map:
  book_name: string
  book_order: integer
  chapter_number: integer
  verse_number: integer
  verse_id: string
  sequential_position: integer
  total_verses_in_chapter: integer
  total_chapters_in_book: integer
  verse_text: string
  verse_length: integer
  contains_cross_references: boolean
  has_footnotes: boolean
  section_title: string
  testament: string
exporter: structured_biblical_json
generated_by: biblical_text_processor
generation_date: "2024-12-19"
algorithm: |
  ## Algoritmo de Segmentación de Texto Bíblico

  ### 1. Preprocesamiento Inicial
  - Normalizar espacios en blanco y saltos de línea múltiples
  - Identificar y marcar títulos en mayúsculas (nombres de libros como "GÉNESIS")
  - Detectar patrones de capítulos con formato "Libro + número" (ej: "Génesis 1")

  ### 2. Detección de Estructura Principal
  - **Identificar libros**: Buscar líneas completamente en mayúsculas que coincidan con nombres bíblicos conocidos
  - **Detectar capítulos**: Localizar patrones que combinen nombre de libro + número (formato: "Nombre ##")
  - **Mapear jerarquía**: Establecer relación libro → capítulo → verso

  ### 3. Segmentación Específica de Versos
  - **Identificar números de verso**: Buscar patrones numéricos al inicio de línea o párrafo (formato: "##." o "##:")
  - **Extraer contenido**: Capturar todo el texto desde el número hasta el siguiente número de verso
  - **Manejar continuaciones**: Unir líneas que pertenecen al mismo verso pero están separadas por saltos de línea
  - **Procesar texto fragmentado**: Detectar versos que continúan en la siguiente línea sin número

  ### 4. Validación y Refinamiento
  - **Verificar secuencia numérica**: Confirmar que los números de verso siguen orden consecutivo
  - **Validar completitud**: Asegurar que cada verso tenga contenido textual válido
  - **Corregir fragmentación**: Unir versos divididos incorrectamente por formato del documento
  - **Limpiar contenido**: Eliminar caracteres especiales y espacios innecesarios del texto del verso

  ### 5. Generación de Metadatos y Estructura Final
  - **Crear identificadores únicos**: Generar IDs con formato "Libro_Capítulo_Verso"
  - **Asignar metadatos**: Para cada verso incluir:
    - Nombre del libro
    - Número de capítulo
    - Número de verso
    - Posición ordinal en el documento
  - **Estructurar salida**: Organizar en formato JSON/XML con jerarquía clara
  - **Generar índices**: Crear mapas de navegación por libro, capítulo y verso

  ### Consideraciones Especiales
  - Manejar variaciones en formato de numeración (puntos, dos puntos, paréntesis)
  - Detectar títulos de secciones o subtítulos que no son versos
  - Procesar referencias cruzadas o notas al pie que puedan interferir
  - Mantener texto original preservando puntuación y formato interno del verso

  ### Salida Esperada
  Cada entrada contendrá: libro, capítulo, número de verso, texto completo del verso, y metadatos de posición para navegación secuencial.