default_metadata:
  content_type: mixed
  source_type: json
description: Para CUALQUIER archivo JSON. Extrae texto de propiedades comunes y aplica
  filtros configurables. Usa la pestaña 'Filtros JSON' para configuración específica.
  Agnóstico al idioma y autor.
json_config:
  date_path: date
  filter_rules: []
  pointer_path: id
  root_array_path: ''
  text_property_paths:
  - content
  - text
  - title
  - message
  - body
  - description
  - data
  treat_as_single_object: false
name: json
output_config:
  include_filter_metadata: true
  include_raw_data: false
  segment_numbering: true
pre_processor: common_block
segmenter: heading
segmenter_config:
  disable_grouping: true
  enable_headings: false
  heading_detection:
    heading_patterns:
    - ^#{1,6}\s+.*$
    - ^[A-ZÁÉÍÓÚÑÜ][^.!?]*:$
    - ^\s*[IVX]+\.\s+.*$
    - ^\s*\d+\.\s+.*$
    max_heading_length: 150
  paragraph_detection:
    min_paragraph_length: 30
    paragraph_break_patterns:
    - ^\s*$
    - ^\s*---\s*$
  preserve_paragraphs: false
  smart_titles: false
