name: "prosa"
description: "Para CUALQUIER contenido en prosa: libros, documentos, artículos, ensayos, textos académicos, narrativa. Detecta automáticamente títulos, capítulos, secciones y párrafos. Agnóstico al idioma y autor."

# Configuración del segmentador
segmenter: "heading"

# Configuración del pre-procesador
pre_processor: "common_block"

# Configuración específica del pre-procesador con fusión inteligente para PDFs
pre_processor_config:
  # Filtrado agresivo habilitado por defecto
  filter_insignificant_blocks: true
  min_block_chars_to_keep: 15               # Bloques menores a 15 caracteres se descartan
  max_single_word_length: 40               # Palabras solas mayores a 40 caracteres se descartan
  discard_only_numbers: true               # Descartar números de página y similares
  discard_common_pdf_artifacts: true       # Descartar preposiciones, artículos sueltos
  
  # Fusión más agresiva para PDFs
  aggressive_merge_for_pdfs: true
  max_vertical_gap_aggressive_pt: 50       # Gap más grande para fusión agresiva (muy agresivo)
  
  # División de párrafos optimizada
  min_chars_for_paragraph_split: 50        # Umbral para dividir por \n\n
  try_single_newline_split_if_block_longer_than: 300
  min_chars_for_single_newline_paragraph: 30
  min_block_area_for_split: 0              # Sin restricción de área para dividir bloques

# Configuración específica del segmentador - CAMBIO: preservar párrafos individuales
segmenter_config:
  # DESACTIVAR agrupación por secciones - tratar cada párrafo como segmento independiente
  disable_section_grouping: true
  preserve_individual_paragraphs: true
  
  # Filtrado adicional en el segmentador
  filter_small_segments: true
  min_segment_length: 25                   # Longitud mínima para crear un segmento
  
  # Configuración para HeadingSegmenter - detección inteligente de títulos y estructura
  heading_detection:
    # ACTIVAR detección inteligente de títulos usando análisis visual y textual
    enable_heading_detection: true
    smart_title_detection: true           # Usar TitleDetector para análisis inteligente
    title_score_threshold: 3.0           # Umbral para clasificar como título (0-10)
    max_hierarchy_levels: 6              # Máximo 6 niveles de jerarquía
    
    # Patrones tradicionales como respaldo
    heading_patterns:
      - "^\\s*(introducción|prefacio|prólogo)\\s*([|].*)?$"
      - "^\\s*(capítulo|chapter)\\s+\\d+.*$"
      - "^\\s*(\\d+\\.)+\\s+.*$"
      - "^\\s*[IVXLCDM]+\\.\\s+.*$"
    max_heading_length: 200
  
  paragraph_detection:
    min_paragraph_length: 25  # Reducido para permitir párrafos más pequeños
    paragraph_break_patterns:
      - "^\\s*$"
      - "^\\s*---\\s*$"
      - "^\\s*\\*\\*\\*\\s*$"

# Configuración de detección automática de autores
author_detection:
  enabled: true                          # Habilitar detección automática de autores
  use_hybrid_detection: true             # Usar el nuevo detector híbrido
  confidence_threshold: 0.5              # Umbral de confianza para prosa (ajustado)
  debug: false                           # Debug de la detección
  fallback_to_override: true             # Si no se detecta, usar author_override
  
  # Nuevas utilidades de detección avanzada
  use_header_footer_filter: true         # Filtrar headers/footers repetitivos
  structural_header_threshold: 0.9       # Umbral para considerar texto como header/footer (90%)
  use_pdf_metadata: true                 # Extraer autor de metadatos PDF
  use_spacy_ner: true                    # Validar con reconocimiento de entidades
  spacy_model: "es_core_news_sm"         # Modelo de spaCy para español
  use_known_authors: true                # Validar contra base de autores conocidos
  known_authors_path: null               # Usar archivo por defecto (null = archivo incluido)
  
  # Configuración específica para el detector híbrido
  hybrid_config:
    enable_literary_database: true       # Habilitar base de datos de autores literarios
    enable_stylometric_analysis: true    # Habilitar análisis estilométrico
    enable_document_context_boost: true  # Habilitar boost por contexto de documento
    literary_authors_priority: true      # Dar prioridad a autores literarios conocidos

# Configuración de metadatos por defecto
default_metadata:
  content_type: "prose"
  # Idioma y autor se configuran con overrides en la UI

# Configuración de salida
output_config:
  include_raw_data: false
  segment_numbering: true