name: "prosa"
description: "Para CUALQUIER contenido en prosa: libros, documentos, artículos, ensayos, textos académicos, narrativa. Detecta automáticamente títulos, capítulos, secciones y párrafos. Agnóstico al idioma y autor."

# Configuración del segmentador
segmenter: "heading"

# Configuración del pre-procesador
pre_processor: "common_block"

# Configuración específica del pre-procesador - OPTIMIZADA PARA DOCUMENTOS LARGOS
pre_processor_config:
  # Filtrado REDUCIDO para documentos largos como el Quijote
  filter_insignificant_blocks: true
  min_block_chars_to_keep: 3                # Permitir bloques muy pequeños cuando son válidos
  max_single_word_length: 60               # AUMENTADO: Palabras solas mayores a 60 caracteres se descartan
  discard_only_numbers: true               # Descartar números de página y similares
  discard_common_pdf_artifacts: false      # DESACTIVADO: No descartar artefactos para preservar contenido
  
  # Fusión MENOS agresiva para preservar estructura
  aggressive_merge_for_pdfs: true
  max_vertical_gap_aggressive_pt: 25       # REDUCIDO: Gap más pequeño para fusión menos agresiva
  
  # División de párrafos más permisiva
  min_chars_for_paragraph_split: 30        # REDUCIDO: Umbral para dividir por \n\n
  try_single_newline_split_if_block_longer_than: 400  # AUMENTADO: Intentar división con salto simple
  min_chars_for_single_newline_paragraph: 20  # REDUCIDO: Párrafos más pequeños permitidos
  min_block_area_for_split: 0              # Sin restricción de área para dividir bloques
  
  # División adicional por salto de línea + mayúscula
  split_on_newline_capital: true
  min_paragraph_length: 10
  
  # NUEVA: Configuración específica para documentos largos
  preserve_long_documents: true            # Preservar contenido completo en documentos largos
  max_consecutive_empty_blocks: 10         # Permitir más bloques vacíos consecutivos antes de parar

# Configuración específica del segmentador - OPTIMIZADA PARA DOCUMENTOS LARGOS
segmenter_config:
  # DESACTIVAR agrupación por secciones - tratar cada párrafo como segmento independiente
  disable_section_grouping: true
  preserve_individual_paragraphs: true
  
  # Filtrado REDUCIDO en el segmentador para documentos largos
  filter_small_segments: false             # No filtrar por longitud
  min_segment_length: 1                    # Aceptar segmentos muy cortos
  
  # NUEVA: Configuración para manejo de espacios en blanco
  max_consecutive_empty_lines: 20          # Permitir hasta 20 líneas vacías consecutivas
  continue_after_large_gaps: true         # Continuar procesamiento después de gaps grandes
  
  # Configuración para HeadingSegmenter - detección inteligente de títulos y estructura
  heading_detection:
    # ACTIVAR detección inteligente de títulos usando análisis visual y textual
    enable_heading_detection: true
    smart_title_detection: true           # Usar TitleDetector para análisis inteligente
    title_score_threshold: 3.0           # Umbral para clasificar como título (0-10)
    max_hierarchy_levels: 6              # Máximo 6 niveles de jerarquía
    
    # Patrones tradicionales como respaldo
    heading_patterns:
      - "^\\s*(introducción|prefacio|prólogo)\\s*([|].*)?$"
      - "^\\s*(capítulo|chapter)\\s+\\d+.*$"
      - "^\\s*(\\d+\\.)+\\s+.*$"
      - "^\\s*[IVXLCDM]+\\.\\s+.*$"
    max_heading_length: 200
  
  paragraph_detection:
    min_paragraph_length: 10
    paragraph_break_patterns:
      - "^\\s*$"
      - "^\\s*---\\s*$"
      - "^\\s*\\*\\*\\*\\s*$"

# Configuración de detección automática de autores
author_detection:
  enabled: true                          # Habilitar detección automática de autores
  use_hybrid_detection: true             # Usar el nuevo detector híbrido
  confidence_threshold: 0.85             # Umbral de confianza MUY ALTO para evitar falsos positivos
  debug: false                           # Debug de la detección
  fallback_to_override: true             # Si no se detecta, usar author_override
  
  # Nuevas utilidades de detección avanzada
  use_header_footer_filter: true         # Filtrar headers/footers repetitivos
  structural_header_threshold: 0.9       # Umbral para considerar texto como header/footer (90%)
  use_pdf_metadata: true                 # Extraer autor de metadatos PDF
  use_spacy_ner: true                    # Validar con reconocimiento de entidades
  spacy_model: "es_core_news_sm"         # Modelo de spaCy para español
  use_known_authors: true                # Validar contra base de autores conocidos
  known_authors_path: null               # Usar archivo por defecto (null = archivo incluido)
  
  # Configuración específica para el detector híbrido
  hybrid_config:
    enable_literary_database: true       # Habilitar base de datos de autores literarios
    enable_stylometric_analysis: true    # Habilitar análisis estilométrico
    enable_document_context_boost: true  # Habilitar boost por contexto de documento
    literary_authors_priority: true      # Dar prioridad a autores literarios conocidos

# Configuración de metadatos por defecto
default_metadata:
  content_type: "prose"
  # Idioma y autor se configuran con overrides en la UI

# Configuración de salida
output_config:
  include_raw_data: false
  segment_numbering: true