name: book_structure
# REGLA: Prohibido el uso de palabras clave o semántica para detectar encabezados. Solo señales estructurales.
description: "Detecta estructura jerárquica en libros y documentos SOLO con señales estructurales (longitud, formato visual, numeraciones, mayúsculas, markdown). Filtro agresivo para PDFs."

# Configuración del segmentador
segmenter: heading

# Configuración del pre-procesador
pre_processor: common_block

# Configuración específica del pre-procesador para PDFs problemáticos
pre_processor_config:
  # Filtrado agresivo habilitado por defecto
  filter_insignificant_blocks: true
  min_block_chars_to_keep: 15               # Bloques menores a 15 caracteres se descartan
  max_single_word_length: 40               # Palabras solas mayores a 40 caracteres se descartan
  discard_only_numbers: true               # Descartar números de página y similares
  discard_common_pdf_artifacts: true       # Descartar preposiciones, artículos sueltos
  
  # Fusión más agresiva para PDFs
  aggressive_merge_for_pdfs: true
  max_vertical_gap_aggressive_pt: 25       # Gap más grande para fusión agresiva
  
  # División de párrafos optimizada pero menos restrictiva
  min_chars_for_paragraph_split: 50        # Umbral más bajo para dividir por \n\n
  try_single_newline_split_if_block_longer_than: 300
  min_chars_for_single_newline_paragraph: 30

# Configuración específica del segmentador
segmenter_config:
  # Filtrado adicional en el segmentador
  filter_small_segments: true
  min_segment_length: 25                   # Longitud mínima para crear un segmento
  
  # Configuración de encabezados
  thresholds:
    max_heading_length: 200                # Longitud máxima para considerar encabezado
    max_section_depth: 3                   # Profundidad máxima de anidación
    min_heading_content: 1                 # Mínimo de bloques para considerar sección
    max_empty_after_heading: 5             # Máximo de líneas vacías tras encabezado
  
  # Habilitar debug para ver estadísticas de filtrado
  debug: false

# Configuración de archivos compatibles
file_types: [".txt", ".md", ".docx", ".pdf"]

# Configuración de metadatos por defecto
default_metadata:
  content_type: "book_structure"
  # Idioma y autor se configuran con overrides en la UI

# Configuración de salida
output_config:
  include_raw_data: false
  segment_numbering: true