name: chapter_heading
description: "Detecta encabezados temáticos y secciones en documentos sin numeración tradicional"

# Configuración del segmentador
segmenter: heading

# Configuración del pre-procesador
pre_processor: common_block

# Configuración específica del pre-procesador con fusión inteligente para PDFs
pre_processor_config:
  # Filtrado agresivo habilitado por defecto
  filter_insignificant_blocks: true
  min_block_chars_to_keep: 15               # Bloques menores a 15 caracteres se descartan
  max_single_word_length: 40               # Palabras solas mayores a 40 caracteres se descartan
  discard_only_numbers: true               # Descartar números de página y similares
  discard_common_pdf_artifacts: true       # Descartar preposiciones, artículos sueltos
  
  # Fusión más agresiva para PDFs
  aggressive_merge_for_pdfs: true
  max_vertical_gap_aggressive_pt: 25       # Gap más grande para fusión agresiva
  
  # División de párrafos optimizada
  min_chars_for_paragraph_split: 50        # Umbral para dividir por \n\n
  try_single_newline_split_if_block_longer_than: 300
  min_chars_for_single_newline_paragraph: 30

# Configuración específica del segmentador
segmenter_config:
  # Filtrado adicional en el segmentador
  filter_small_segments: true
  min_segment_length: 25                   # Longitud mínima para crear un segmento

# Configuración de archivos compatibles
file_types: [".docx", ".txt", ".md", ".pdf"]

# Configuración de umbrales
thresholds:
  max_heading_length: 200      # Longitud máxima para considerar encabezado (mayor que el perfil book_structure)
  max_section_depth: 4         # Profundidad máxima de anidación
  min_heading_content: 1       # Mínimo de bloques para considerar sección (menor que el perfil book_structure)
  max_empty_after_heading: 5   # Máximo de líneas vacías tras encabezado

# Patrones de encabezados
heading_patterns:
  - "^[A-Z][A-ZÁ-Ú ]{2,}$"     # TÍTULO EN MAYÚSCULAS
  - "^[A-Z][A-ZÁ-Ú ]{2,}\\.+"  # TÍTULO EN MAYÚSCULAS seguido de puntos
  - "^[A-Z][\\w ]{0,30}\\.\\.\\." # Título con puntos suspensivos
  - "^[A-ZÁ-Ú][\\w ]{0,40}:"   # Títulos con formato "Palabra: texto"
  - "^(Naturaleza|Capacidad|Libertad|Impulsos|La|El|Los|Las|Cómo|Génesis) [\\w ]{2,}" # Patrones comunes en el documento

# Configuración de salida
flat: true  # Convertir la estructura jerárquica en una lista plana
post_processor: text_normalizer
post_processor_config:
  min_length: 10               # Longitud mínima para conservar unidad

# Mapeo de metadatos
metadata_map:                  # Mapeo de campos internos a nombres finales
  titulo: title
  nivel: level
  contenido: content
  subsecciones: subsections

# Exportador
exporter: ndjson 