compatibility:
  min_pipeline_version: 1.0.0
  supported_file_formats:
  - .pdf
  - .docx
  - .txt
  - .md
  - .json
  - .ndjson
  supported_profiles:
  - json
  - prosa
  - verso
  - automático
  validate_compatibility: true
deduplication:
  database_path: dataset/data/deduplication.db
  default_output_mode: biblioperson
  enabled: false
  error_handling:
    continue_on_error: true
    log_errors: true
    warn_when_disabled: false
logging:
  include_stats: true
  level: INFO
  show_progress: true
migration:
  auto_migrate: true
  backup_before_migration: true
  backup_directory: dataset/backups/deduplication
output_modes:
  biblioperson:
    description: Salida NDJSON enriquecida con metadatos completos y deduplicación
    enable_deduplication: true
    include_document_hash: true
    included_fields: all
  generic:
    description: Salida NDJSON simple sin metadatos adicionales
    enable_deduplication: false
    included_fields:
    - segment_id
    - document_id
    - text
    - segment_type
    - segment_order
    - text_length
    - processing_timestamp
    - source_file_path
    - document_title
    - document_author
    - document_language
    - pipeline_version
    - segmenter_used
performance:
  enable_hash_cache: true
  hash_chunk_size: 8192
  max_cache_size: 1000
  operation_timeout: 30
